export const maestros = [
    {
        nombre: "Roberto Rangel",
        materia: "Topicos Avanzados ",
        academia: "ISC",
        grupo: "TOPIC",
        rfc: "11111",
        catDominioA: 0,
        catPlanificacionB: 0,
        catAmbientesC: 0,
        catEstrategiasD: 0,
        catMotivacionE: 0,
        catEvaluacionF: 0,
        catComunicacionG: 0,
        catGestionH: 0,
        catTicsI: 0,
        catSatisfaccionJ: 0,

    },
    {
        nombre: "Veronica Sobrevilla",
        materia: "Ingenieria de software",
        academia: "ISC",
        grupo: "IS",
        rfc: "22222",
        catDominioA: 0,
        catPlanificacionB: 0,
        catAmbientesC: 0,
        catEstrategiasD: 0,
        catMotivacionE: 0,
        catEvaluacionF: 0,
        catComunicacionG: 0,
        catGestionH: 0,
        catTicsI: 0,
        catSatisfaccionJ: 0,
    },
    {
        nombre: "Rosa Pelayo",
        materia: "Redes de Computadora",
        academia: "ISC",
        grupo: "RED",
        rfc: "33333",
        catDominioA: 0,
        catPlanificacionB: 0,
        catAmbientesC: 0,
        catEstrategiasD: 0,
        catMotivacionE: 0,
        catEvaluacionF: 0,
        catComunicacionG: 0,
        catGestionH: 0,
        catTicsI: 0,
        catSatisfaccionJ: 0,
    },
    {
        nombre: "Paulino Ramirez",
        materia: "Interfaz Graficas",
        academia: "ISC",
        grupo: "IGE",
        rfc: "44444",
        catDominioA: 0,
        catPlanificacionB: 0,
        catAmbientesC: 0,
        catEstrategiasD: 0,
        catMotivacionE: 0,
        catEvaluacionF: 0,
        catComunicacionG: 0,
        catGestionH: 0,
        catTicsI: 0,
        catSatisfaccionJ: 0,
    }
]
